pipeline {
    agent any
    stages {
        stage("Clean ups") {
            steps {
                deleteDir()
            }
        }
        stage('Clone repo') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'c71bcacf-6b48-4ba3-94a8-e8116a338e47', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/main']],
                              userRemoteConfigs: [[
                                  url: 'https://github.com/azotamiota/dummy-mug.git',
                                  credentialsId: 'c71bcacf-6b48-4ba3-94a8-e8116a338e47'
                              ]]])
                }
            }
        }
        stage("Build") {
            steps {
                dir("dummy-mug") {
                    sh "echo 'Test text in a txt file' > test.txt"
                }
            }
        }
        stage("Test") {
            steps {
                dir('dummy-mug') {
                script {
                        if (fileExists('tessst.txt')) {
                            echo "The file 'test.txt' exists."
                            // Add your test steps here
                        } else {
                            error "The file 'test.txt' does not exist."
                        }
                    }
                }
            }
        }
    }
}